name = "dokinomicon-app"
compatibility_date = "2026-03-12"
main = "./src/worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"

[[routes]]
pattern = "www.duck-automata.com/dokinomicon"
zone_name = "duck-automata.com"

[[routes]]
pattern = "www.duck-automata.com/dokinomicon/*"
zone_name = "duck-automata.com"

[env.dev]
name = "dokinomicon-dev"

[[env.dev.routes]]
pattern = "dev.duck-automata.com/dokinomicon"
zone_name = "duck-automata.com"

[[env.dev.routes]]
pattern = "dev.duck-automata.com/dokinomicon/*"
zone_name = "duck-automata.com"
